version: '3.8'

services:
  yggdrasil:
    build: .
    network_mode: host
    expose:
      - 8080:8080
    healthcheck:
      test: ['CMD-SHELL', 'curl http://localhost:8080']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./src:/app/src
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # https://github.com/keycloak/keycloak/issues/10216
      JAVA_OPTS_APPEND: |
        -Dkeycloak.migration.action=import
        -Dkeycloak.migration.provider=singleFile
        -Dkeycloak.migration.file=/opt/keycloak/data/realm.json
        -Dkeycloak.migration.strategy=IGNORE_EXISTING
        -Dkeycloak.migration.replace-placeholders=true
        -Dkeycloak.profile.feature.upload_scripts=enabled
    volumes:
      - ./config/realm-import.json:/opt/keycloak/data/realm.json:ro
    ports:
      - 8180:8080

  # Oracle service (label used to access the service container)
  oracle:

    # Docker Hub image (feel free to change the tag "latest" to any other available one)
    # image: gvenzl/oracle-xe
    image: gvenzl/oracle-free

    # Provide passwords and other environment variables to container
    environment:
      ORACLE_PASSWORD: admin
      # ORACLE_DATABASE: admin
      # ORACLE_RANDOM_PASSWORD: true
      # APP_USER: admin
      # APP_USER_PASSWORD: admin

    # Forward Oracle port
    ports:
      - 1521:1521

    # Provide healthcheck script options for startup
    # options: >-
    #   --health-cmd healthcheck.sh
    #   --health-interval 10s
    #   --health-timeout 5s
    #   --health-retries 10
