name: Build and push a branch image to ghcr

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: msga-mmm/yggdrasil

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name for docker image tags
        id: extract_branch
        run: |
          # Extract the branch name from GITHUB_REF
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          # Replace any slashes with dashes
          BRANCH_NAME=${BRANCH_NAME//\//-}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/msga-mmm/yggdrasil:${{ env.BRANCH_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
