name: Build and push a branch image to ghcr

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: write
      checks: write
      contents: write
      deployments: write
      pages: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/msga-mmm/yggdrasil:dev-${{ github.sha }}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
